name: features_cart
description: Cart feature
version: 0.1.0
publish_to: none
environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  go_router: ^14.2.0
  equatable: ^2.0.5
  mvs_shared_ui:
    path: ../../shared_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
