name: features_home
description: Home feature
version: 0.1.0
publish_to: none
environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.0
  flutter_bloc: ^8.1.4
  get_it: ^7.6.0
  mvs_core:
    path: ../../core
  mvs_shared_ui:
    path: ../../shared_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
