name: features_account
description: Account feature
version: 0.1.0
publish_to: none
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  go_router: ^14.2.0
  get_it: ^7.6.0
  mvs_core:
    path: ../../core
  features_auth:
    path: ../auth

dev_dependencies:
  flutter_test:
    sdk: flutter
